### ISSUE TITLE
4张3090能训练llama13B么，我做了尝试但是失败了

### ISSUE THREAD

**Issue by cc2017111** [OpenLMLab/LOMO#10]

**Comment by ayyyq** [comment]
你好，使用如下配置和命令，是可以在4张3090上训练LLaMA-13B的。需要注意的是，该`batch_size`开得过大，并不能优化出WIC数据集上的最优结果。
```
# model
model_name_or_path: '/remote-home/share/llama_hf/13B'
# data
dataset_name: 'wic'
refresh: false
data_tag: 'base'
train_on_inputs: false
data_max_length: 1024
# training
# trainer
tag: 'lomo'
output_dir: 'outputs'
overwrite_output_dir: true
deepspeed: 'config/ds_config.json'
do_train: true
do_eval: true
evaluation_strategy: 'epoch'
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
learning_rate: 0.03
weight_decay: 0
num_train_epochs: 10
lr_scheduler_type: 'linear'
warmup: 0.1
clip_grad_norm: 1.0
save_strategy: 'no'
save_total_limit: 0
seed: 42
#bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: false
```
```
deepspeed --master_port 25000 --include localhost:4,5,6,7 src/train_lomo.py config/args_lomo.yaml
```
如果仍然遇到`CUDA Out of Memory`的问题，可以提供你的配置，我们会尽可能帮你解决。:)

**Comment by 00drdelius** [comment]
> 你好，使用如下配置和命令，是可以在4张3090上训练LLaMA-13B的。需要注意的是，该`batch_size`开得过大，并不能优化出WIC数据集上的最优结果。
> 
> ```
> # model
> model_name_or_path: '/remote-home/share/llama_hf/13B'
> # data
> dataset_name: 'wic'
> refresh: false
> data_tag: 'base'
> train_on_inputs: false
> data_max_length: 1024
> # training
> # trainer
> tag: 'lomo'
> output_dir: 'outputs'
> overwrite_output_dir: true
> deepspeed: 'config/ds_config.json'
> do_train: true
> do_eval: true
> evaluation_strategy: 'epoch'
> per_device_train_batch_size: 16
> per_device_eval_batch_size: 16
> learning_rate: 0.03
> weight_decay: 0
> num_train_epochs: 10
> lr_scheduler_type: 'linear'
> warmup: 0.1
> clip_grad_norm: 1.0
> save_strategy: 'no'
> save_total_limit: 0
> seed: 42
> #bf16: true
> remove_unused_columns: false
> load_best_model_at_end: false
> metric_for_best_model: 'acc'
> group_by_length: false
> #report_to: 'wandb'
> dataloader_pin_memory: false
> gradient_checkpointing: true
> predict_with_generate: false
> ```
> 
> ```
> deepspeed --master_port 25000 --include localhost:4,5,6,7 src/train_lomo.py config/args_lomo.yaml
> ```
> 
> 如果仍然遇到`CUDA Out of Memory`的问题，可以提供你的配置，我们会尽可能帮你解决。:)

为啥我增加batch size为2或以上就会不停地3提示我gradient overflow直到loss scale reaches limit...

**Comment by valkryhx** [comment]
不如用qlora 一张24g卡就能调llama13b 效果也不差

**Comment by KaiLv69** [comment]
Feel free to reopen this issue if any further problems.
