### ISSUE TITLE
目前支持ChatGLM吗？我一直报错：NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by doubleguy** [OpenLMLab/LOMO#11]
我尝试使用LOMO对ChatGLM进行全量训练，但是模型加载部分一直报错NotImplementedError: Cannot copy out of meta tensor; no data!
出问题得代码位置在model = AutoModel.from_pretrained(model_args.model_name_or_path, trust_remote_code=True).half().cuda()这一句。

**Comment by doubleguy** [comment]
找到解决办法了，需要加入empty_init=False，chatglm在deepspeed中运行有时会出现这个问题。

**Comment by NLPpupil** [comment]
这个解决办法也适用于chatglm2
