### ISSUE TITLE
4070ti有机会训练一下吗

### ISSUE THREAD

**Issue by EveningLin** [OpenLMLab/LOMO#17]
OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 11.73 GiB total capacity; 9.55 GiB already allocated; 43.31 MiB free; 10.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated
memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by KaiLv69** [comment]
11G显存大概能训练opt-2.7b, bloom-3b这种大小的模型，你可以尝试一下。
