### ISSUE TITLE
我理解是分批次进GPU内存再计算，而速度怎么做到没有下降的？太强了

### ISSUE THREAD

**Issue by guotong1988** [OpenLMLab/LOMO#19]
<img width="829" alt="image" src="https://github.com/OpenLMLab/LOMO/assets/4702353/9e50eff8-6111-4236-98e5-9e425f921272">

**Comment by QipengGuo** [comment]
不是分批次，不同于offload，参数本身都在GPU上，没有移动成本，具体原理欢迎阅读我们的paper。

**Comment by guotong1988** [comment]
![image](https://github.com/OpenLMLab/LOMO/assets/4702353/2db4287d-db0a-424f-99b6-e1054016fbc3)

这个图有个Off Memory

**Comment by KaiLv69** [comment]
你好，这里的Off Memory是指不占用显存了。
梯度从Off Memory->In Memory的过程是在反向传播过程中逐步计算出梯度（不是从CPU移动到GPU）；
梯度从In Memory->Off Memory的过程是算出来梯度就拿来更新参数，然后就把梯度置为None（不是从GPU移动到CPU）。

**Comment by guotong1988** [comment]
> 这里的Off Memory是指不占用显存了。

Off Memory和In Memory的时候，梯度和参数都存在什么地方？

**Comment by KaiLv69** [comment]
参数一直都存在显存里，梯度的Off Memory指的是为None，显存内存里都不占空间

**Comment by QipengGuo** [comment]
换个说法就是梯度释放了，更新完就不需要了。
