### ISSUE TITLE
看了下lomo的代码实现，训练的速度会很慢吗？

### ISSUE THREAD

**Issue by egptee** [OpenLMLab/LOMO#22]
看了下注册hook的方式，这是否相当于每次backpropagation的时候，每触发一个变量的求导，就要for循环遍历一次全部参数。 对于一个几十亿参数量的模型。这种计算方式会不会导致训练的速度非常慢？

**Comment by QipengGuo** [comment]
是循环遍历所有的参数张量，一般几百个左右，不是逐个参数遍历的。其实是可以根据计算图知道每次触发要更新哪个参数的，不过遍历的代码比较简单，并且开销很小，我们就选用了这种实现。
