### ISSUE TITLE
wandb permission

### ISSUE THREAD

**Issue by season1blue** [OpenLMLab/LOMO#23]
您好，感谢您的开源。
我在运行sh run.sh的时候出现了以下错误，我需要加入什么来获得权重授权吗？

wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
Problem at: src/train_lomo.py 78 train
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "src/train_lomo.py", line 125, in <module>
    train()
  File "src/train_lomo.py", line 78, in train
    config=wandb_config
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    raise e
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no 
issues with your networking setup.(Error 404: Not Found)

**Comment by ayyyq** [comment]
你好！请将wandb的`project`和`entity`换成自己的账号，或者设置环境变量`WANDB_MODE=disabled`以关闭wandb。

**Comment by shi-kejian** [comment]
Hi, I had the same issue. An easy fix for me is to remove these two lines https://github.com/OpenLMLab/LOMO/blob/ee7d431344569bc69ff7283b70141b5c6d66c901/src/train_lomo.py#L75-L76
Then wandb should log the run to your default project.

**Comment by season1blue** [comment]
感谢帮助！

**Comment by Xuekai-Zhu** [comment]
The following code also works for me
```
wandb.login()
wandb.init(
            dir=wandb_dir,
            project="olma",
            name="test",
            # group=cfg.wandb.group,
            # name=cfg.wandb.name,
            # tags=cfg.wandb.tags,
            config=cfg.asdict(exclude=["wandb"]),
            
        )
```
