### ISSUE TITLE
LORA+LOMO distributed learning

### ISSUE THREAD

**Issue by Jiaxiangren** [OpenLMLab/LOMO#33]
感谢您的工作，我这有个问题是为什么现有的提供的lomo+lora的代码不支持分布式训练。
<img width="709" alt="image" src="https://github.com/OpenLMLab/LOMO/assets/31751000/14b3146c-9f7b-42c2-b49b-7005dd035ed6">
我注释掉了上面两行，程序依旧可以运行。

**Comment by KaiLv69** [comment]
你好。我们验证了lora+lomo的单卡有效性，分布式环境下代码能跑但是可能有bug。

**Comment by Jiaxiangren** [comment]
xie xie !
