### ISSUE TITLE
Gradient accumulation 

### ISSUE THREAD

**Issue by EladDv** [OpenLMLab/LOMO#4]
Is gradient accumulation still mathematically possible in this scheme?
Because if so we could train 65b on a single 3090 in a day and a half

**Comment by QipengGuo** [comment]
No, the gradient is no longer perseved in the GPU memory. If you offload the gradient tensor to the CPU memory or NVME, there is a large cost of transportation.

**Comment by KaiLv69** [comment]
Based on the information provided, we consider this issue resolved. If you have any further questions or concerns, please reopen this issue and provide additional details.
