### ISSUE TITLE
关于微调llama-65b的疑问

### ISSUE THREAD

**Issue by Facico** [OpenLMLab/LOMO#40]
非常nice的工作！不过有几个问题想询问一下。

在代码train_lomo.py中是使用transformers自带的AutoModelForCausalLM来加载的，然后在trainer中再使用的deepspeed来处理模型。就是应该是先让模型在每张卡加载上，再使用zero3来优化。但是3090应该是在加载65B的过程中就OOM了

想问一下这里说的8张3090能全量微调65B，是使用了collie中的张量并行+LOMO吗？还是就用这个repo的代码就能实现了

Thanks！

**Comment by KaiLv69** [comment]
你好。LOMO与张量并行和ZeRO-3都能结合起来使用，这个repo里目前使用的是ZeRO-3（张量并行版本的部分模型也计划加入此repo）。

在用ZeRO-3初始化模型的时候并不是先把模型在每张卡上都加载，在`from_pretrained()`的过程中就会把参数切分以加载。这个repo的代码就可以实现8张3090全量微调llama-65b。

**Comment by Facico** [comment]
感谢
