### ISSUE TITLE
batch size开2后一直提示gradient overflow。。

### ISSUE THREAD

**Issue by 00drdelius** [OpenLMLab/LOMO#42]
batch_size 为1的时候很正常地训练着；
之前都没试过bsz开2，今天试了下却出现下图的情况真不知道怎么回事了。。

![37284011428a932f14f865964a5f67f](https://github.com/OpenLMLab/LOMO/assets/88967316/9456dbfa-b728-4b2f-bd7e-28be6e0dde19)

**Comment by is** [comment]
这个情况，应该没太大问题吧，自适应的，再等几步就好了。
可以通过deepspeed config设置初始值。

**Comment by 00drdelius** [comment]
> 这个情况，应该没太大问题吧，自适应的，再等几步就好了。
> 
> 可以通过deepspeed config设置初始值。

我的不行呀。自适应到1然后就报错了。还试过调精度为bf16和fp32都是一样的。只有bsz为1才没问题

**Comment by is** [comment]
LOMO 优化器能直接设置scaler的吧，我看代码，设置成1试试。
错误信息是什么？
你是用什么卡训练啊？bsz变大了，大概率还是内存不够用吧?

**Comment by 00drdelius** [comment]
> LOMO 优化器能直接设置scaler的吧，我看代码，设置成1试试。
> 
> 错误信息是什么？
> 
> 你是用什么卡训练啊？bsz变大了，大概率还是内存不够用吧?

没有报错，就是正常的提示gradient overflow，然后就会跳过这个step直接到下一个step，然后继续提示overflow。

配置是3张3090，炼的baichuan-13B应该是够的呀。
问题出在grad norm函数内检测是否存在inf或nan的梯度，其实可以试下换clip norm换clip value，可以试试但应该大概率没用。
现在还在跑qlora，之后在测测。

**Comment by is** [comment]
那，确实，比较烦了。

我现在用collie里面moss的基准example，是能凑合跑起来的. 
tp_size=2,dp_size=1

**Comment by is** [comment]
我用
https://github.com/hiyouga/LLaMA-Efficient-Tuning/
这个代码，全参数训练baichuan-13b，也是碰到同样的问题，
per_device_train_batch_size 只要不等于1, gradient overflow

不知道是不是baichuan-13b计算loss的代码有问题.

**Comment by 00drdelius** [comment]
> 我用 https://github.com/hiyouga/LLaMA-Efficient-Tuning/ 这个代码，全参数训练baichuan-13b，也是碰到同样的问题， per_device_train_batch_size 只要不等于1, gradient overflow
> 
> 不知道是不是baichuan-13b计算loss的代码有问题.
> 
> ```
> 
> [INFO|trainer.py:1786] 2023-07-19 09:01:30,832 >> ***** Running training *****                                                                                                    
> [INFO|trainer.py:1787] 2023-07-19 09:01:30,833 >>   Num examples = 19,891                                                                                                         
> [INFO|trainer.py:1788] 2023-07-19 09:01:30,833 >>   Num Epochs = 3                                                                                                                
> [INFO|trainer.py:1789] 2023-07-19 09:01:30,833 >>   Instantaneous batch size per device = 2                                                                                       
> [INFO|trainer.py:1790] 2023-07-19 09:01:30,833 >>   Total train batch size (w. parallel, distributed & accumulation) = 32                                                         
> [INFO|trainer.py:1791] 2023-07-19 09:01:30,833 >>   Gradient Accumulation steps = 4                                                                                               
> [INFO|trainer.py:1792] 2023-07-19 09:01:30,833 >>   Total optimization steps = 1,863                                                                                              
> [INFO|trainer.py:1793] 2023-07-19 09:01:30,834 >>   Number of trainable parameters = 13,264,901,120     
> 
>   0%|                                                                                                                                                    | 0/1863 [00:00<?, ?it/s]
> [2023-07-19 09:01:36,548] [INFO] [loss_scaler.py:190:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 256, but hysteresis is 2. Reducing hysteresis
>  to 1                                                                                                                                                                             
>   0%|                                                                                                                                          | 1/1863 [00:05<2:57:21,  5.71s/it]
> [2023-07-19 09:01:38,976] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 256, reducing to 128                         
>   0%|▏                                                                                                                                         | 2/1863 [00:08<1:57:17,  3.78s/it]
> [2023-07-19 09:01:41,373] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 128, reducing to 64                          
>   0%|▏                                                                                                                                         | 3/1863 [00:10<1:37:37,  3.15s/it]
> [2023-07-19 09:01:44,387] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 64, reducing to 32                           
>   0%|▎                                                                                                                                         | 4/1863 [00:13<1:35:54,  3.10s/it]
> [2023-07-19 09:01:46,822] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 32, reducing to 16                           
>   0%|▎                                                                                                                                         | 5/1863 [00:15<1:28:29,  2.86s/it]
> [2023-07-19 09:01:49,232] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 16, reducing to 8                            
>   0%|▍                                                                                                                                         | 6/1863 [00:18<1:23:43,  2.71s/it]
> [2023-07-19 09:01:51,648] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 8, reducing to 4                             
>   0%|▌                                                                                                                                         | 7/1863 [00:20<1:20:45,  2.61s/it]
> [2023-07-19 09:01:54,083] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 4, reducing to 2                             
>   0%|▌                                                                                                                                         | 8/1863 [00:23<1:18:59,  2.55s/it]
> [2023-07-19 09:01:56,504] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 2, reducing to 1                             
>   0%|▋     
> 
> Current loss scale already at minimum - cannot decrease scale anymore. Exiting run.
> ```

那你试过其他的模型有没有出现过相同的问题？
还是单单baichuan-13B出现了这个问题

**Comment by is** [comment]
@00drdelius 
完全相同的配置和数据集，把model_name_or_path直接换成openlm-research/open_llama_13b
就没问题，你可以试试。

**Comment by KaiLv69** [comment]
您好，`fp16`表示数值范围有限，这个是在`backward`算梯度过程中出现了溢出，还没有到更新模型权重的那一步。可能的解决办法是更换到`bf16`。

**Comment by 00drdelius** [comment]
> 您好，`fp16`表示数值范围有限，这个是在`backward`算梯度过程中出现了溢出，还没有到更新模型权重的那一步。可能的解决办法是更换到`bf16`。

我试过改成bf16甚至fp32，但都出现了溢出而且仅限baichuan13B  bsz>=2，恐怕不是精度的问题。

**Comment by KaiLv69** [comment]
> 我试过改成bf16甚至fp32，但都出现了溢出而且仅限baichuan13B bsz>=2，恐怕不是精度的问题。

可能是模型和数据不太匹配？可以通过不初始化优化器，仅forward和backward来确定一下。

**Comment by 00drdelius** [comment]
> > 我试过改成bf16甚至fp32，但都出现了溢出而且仅限baichuan13B bsz>=2，恐怕不是精度的问题。
> 
> 可能是模型和数据不太匹配？可以通过不初始化优化器，仅forward和backward来确定一下。

我还在处理其他数据集。之后还要用LOMO继续炼baichuan13B的模型，我弄完后一步步调试试下问题出在哪里。

**Comment by is** [comment]
huggingface上Baichuan-13B-Base/Chat都更新了一下model的代码，我pull回来之后，pre node batch size >= 2 梯度溢出的问题好像就好了。我不是很确认，大家可以试试新的。

**Comment by 00drdelius** [comment]
> huggingface上Baichuan-13B-Base/Chat都更新了一下model的代码，我pull回来之后，pre node batch size >= 2 梯度溢出的问题好像就好了。我不是很确认，大家可以试试新的。

9天前的吗？👇
baichuan-13b-chat:
![image](https://github.com/OpenLMLab/LOMO/assets/88967316/1ed72315-dc27-4b7f-93ed-ec2c915065c1)

**Comment by 00drdelius** [comment]
> huggingface上Baichuan-13B-Base/Chat都更新了一下model的代码，我pull回来之后，pre node batch size >= 2 梯度溢出的问题好像就好了。我不是很确认，大家可以试试新的。

哦我看到了。modeling_baichuan.py，我试试。

**Comment by 00drdelius** [comment]
测试完成。更新hf上baichuan-13b新版本的modeling_baichuan.py后不再出现gradient overflow的问题。
原因如下：
![image](https://github.com/OpenLMLab/LOMO/assets/88967316/2905c45b-4503-46c2-a3d9-20157fe36580)
alibi位置编码的问题。

我测试用原来的baichuan-13b的modeling_baichuan.py时，将dataset与collator的padding_side都改成right后也不再出现此问题。
