### ISSUE TITLE
model merge error

### ISSUE THREAD

**Issue by shawnricecake** [OpenLMLab/LOMO#59]
Hi,

I can not get the same results after using 'merge_llama_with_lora.py'

The eval results are different, and the saved savetensors are always 0.5

Thanks

**Comment by KaiLv69** [comment]
Hi, are the merged weights all 0.5? What about the weights (of base model and lora), are they normal?

**Comment by shawnricecake** [comment]
> Hi, are the merged weights all 0.5? What about the weights (of base model and lora), are they normal?

Hi, the eval acc is always 0.5, I did not check the weights yet...

**Comment by KaiLv69** [comment]
merge的过程应该是没问题的，可能是保存模型的问题。请问训练过程中eval的acc是多少？

**Comment by shawnricecake** [comment]
> merge的过程应该是没问题的，可能是保存模型的问题。请问训练过程中eval的acc是多少？

训练过程中，10个epoch，最高可以到0.67。我对模型进行了一些改动（增加了quantization），但是对weights 应该没有影响。。。

**Comment by shawnricecake** [comment]
我尝试了原版本code，在save model 之后，eval merge model 是0.5，保存模型(with lora)还是有问题。。。

**Comment by KaiLv69** [comment]
你是lora+lomo一起训练的吗？如果是这样的话，测一下不merge的model性能怎么样呢？BTW，保存的是10个epoch中最高的那个权重吗？

**Comment by shawnricecake** [comment]
> 你是lora+lomo一起训练的吗？如果是这样的话，测一下不merge的model性能怎么样呢？BTW，保存的是10个epoch中最高的那个权重吗？

你好，是lora+lomo一起训练的，保存的是最高的那个epoch，不merge的model 看起来load有问题（我查看了 pytorch_model.bin 是有13g 大小的）

error是这样
```
Traceback (most recent call last):
  File "src/train_lomo_lora.py", line 182, in <module>
    train()
  File "src/train_lomo_lora.py", line 93, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/models/auto/auto_factory.py", line 516, in from_pretrained
    return model_class.from_pretrained(
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/modeling_utils.py", line 3091, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/modeling_utils.py", line 3335, in _load_pretrained_model
    model.apply(model._initialize_weights)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 884, in apply
    module.apply(fn)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 884, in apply
    module.apply(fn)
  File "/home/sx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 885, in apply
    fn(self)
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/modeling_utils.py", line 1280, in _initialize_weights
    self._init_weights(module)
  File "/data/sx/gpt-quant/gpt-finetune/src/transformers/models/llama/modeling_llama.py", line 477, in _init_weights
    module.weight.data[module.padding_idx].zero_()
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

**Comment by KaiLv69** [comment]
好的，我会尝试复现一下这个问题。

**Comment by shawnricecake** [comment]
Thanks

**Comment by shawnricecake** [comment]
Hi, 

For lomo+lora, the merged model can not achieve same results in eval

I have found the bug: the unmatch name of layers in state dict.

So, the my solution here is that resave the base model checkpoint like here:

```
temp_model = torch.load(model_name_or_path+"/pytorch_model.bin")
    resave_pytorch_model = OrderedDict()
    for e in temp_model:
        if 'base_model.model.' in e:
            resave_pytorch_model[e[(len('base_model.model.')):]] = temp_model[e]
            continue
        resave_pytorch_model[e] = temp_model[e]

    torch.save(resave_pytorch_model, model_name_or_path+"resave/pytorch_model.bin")
```

then, copy the 'config.json' in 'model_name_or_path' to 'model_name_or_path+/resave/' and  load the 'base' in merge_llama_with_lora.py like the following:
```
base = AutoModelForCausalLM.from_pretrained(
        model_name_or_path+'/resave/', 
        low_cpu_mem_usage=True
    )
```

Thanks
Xuan

**Comment by KaiLv69** [comment]
Thanks for your work :) It may be better to change the name here and we can save the disk for the resaved model.
https://github.com/OpenLMLab/LOMO/blob/ea7979d5b70760fafba8264d0c902c01f087f75b/lomo/src/lomo_lora_trainer.py#L518-L520

**Comment by shawnricecake** [comment]
Hi, thanks for your response yet.

I noticed that you uploaded the new code for adaLOMO work and I found that it improved a lot.

May I know that is it necessary for me to use Ampere GPU to run the new adaLOMO?

Thanks
Xuan

**Comment by KaiLv69** [comment]
Hi, thank you for your interest.
1. It is possible. But I don't think it's necessary to add LoRA and I didn't implement it.
2. There is no need to get an Ampere GPU for AdaLomo.

**Comment by KaiLv69** [comment]
1. AdaLomo (or LOMO) + LoRA indeed increases GPU memory consumption compared to AdaLomo (or LOMO) itself. It takes more space for LoRA optimization.
2. Sure, the mechanism are similar.

**Comment by shawnricecake** [comment]
> 1. AdaLomo (or LOMO) + LoRA indeed increases GPU memory consumption compared to AdaLomo (or LOMO) itself. It takes more space for LoRA optimization.
> 2. Sure, the mechanism is similar.

Hi,
For 1. I find if it is LOMO+LoRA, the number of trainable parameters is very small.
I mean that if I use the code of train_lomo_lora.py, it looks like only lora is working.

Xuan

**Comment by KaiLv69** [comment]
> Hi,
> 
> For lomo+lora, the merged model can not achieve same results in eval
> 
> I have found the bug: the unmatch name of layers in state dict.
> 
> So, the my solution here is that resave the base model checkpoint like here:
> 
> ```
> temp_model = torch.load(model_name_or_path+"/pytorch_model.bin")
>     resave_pytorch_model = OrderedDict()
>     for e in temp_model:
>         if 'base_model.model.' in e:
>             resave_pytorch_model[e[(len('base_model.model.')):]] = temp_model[e]
>             continue
>         resave_pytorch_model[e] = temp_model[e]
> 
>     torch.save(resave_pytorch_model, model_name_or_path+"resave/pytorch_model.bin")
> ```
> 
> then, copy the 'config.json' in 'model_name_or_path' to 'model_name_or_path+/resave/' and load the 'base' in merge_llama_with_lora.py like the following:
> 
> ```
> base = AutoModelForCausalLM.from_pretrained(
>         model_name_or_path+'/resave/', 
>         low_cpu_mem_usage=True
>     )
> ```
> 
> Thanks Xuan

Close the issue since the merge error is solved. Please open another issue or disscussion for other problems.
