### ISSUE TITLE
cannot find adalomo class

### ISSUE THREAD

**Issue by Yeojoon** [OpenLMLab/LOMO#60]
In adalomo/instruction-tuning/train.py, AdaLomo is imported from collie.optim but I cannot such optimizer from collie.optim. Would it be possible to help me with finding the implementation of AdaLomo? Thanks!

**Comment by KaiLv69** [comment]
Hi, AdaLomo now is implemented in the `dev` branch of collie. It may take some time to merge into the `main` branch. You can install the `dev` branch and have a try :)

**Comment by Yeojoon** [comment]
oh I see. Thank you for your kind reply!
