### ISSUE TITLE
Evaluation of Fine-tuned model with Adalomo

### ISSUE THREAD

**Issue by sglucas** [OpenLMLab/LOMO#62]
As you mentioned in the paper, you try to evaluate the instruction fine-tuned model on MMLU, BBH, GSM8K, HumanEval, AlpacaFarm ... May I ask the how to evaluate the model on these datasets and reproduce the results on the paper.

Best regards,
Lucas

**Comment by KaiLv69** [comment]
Hi, you can refer to the `Evaluation` section of `adalomo/README.md`.
