### ISSUE TITLE
Instructions for evaluation datasets

### ISSUE THREAD

**Issue by KaiLv69** [OpenLMLab/LOMO#64]
Hi,

Thanks for your help, I can run the finetune with alpaca datasets now, this one should be the AlpacaFarm in the paper, right?

By the way, do you mind provide the instructions for other datasets? like MMLU, BBH, GSM8K, HumanEval

Thanks
Xuan

_Originally posted by @shawnricecake in https://github.com/OpenLMLab/LOMO/issues/63#issuecomment-1785545543_

**Comment by KaiLv69** [comment]
@shawnricecake 
The instructions can be found in `configs/datasets` folder, e.g.
https://github.com/KaiLv69/opencompass/blob/main/configs/datasets/gsm8k/gsm8k_gen_collie.py

**Comment by KaiLv69** [comment]
We only train the model on alpaca dataset and eval the trained model on various benchmarks.

**Comment by shawnricecake** [comment]
> We only train the model on alpaca dataset and eval the trained model on various benchmarks.

lol, awesome!
